# Config deployment
apiVersion: apps/v1 # Define a versão da API do kubernetes usada para este recurso
kind: Deployment # Especifica o tipo de recurso que esta sendo definido, neste caso, um deployment

metadata: # contem informações identificadores sobre o recurso
  labels: # define rótulos associados ao deployment. O rotulo app:  pode ser usado para agrupar ou identificar os recursos selecionados
    app: nginx-deployment
  name: nginx # Define o nome do deployment como nginx
spec: # define as especificações desejadas para o deployment
  replicas: 3  # especifica o numero de replicas do pod que o deployment deve manter. aqui sao 3 replicas
  selector: # define como o deployment encontra os pods gerenciados
    matchLabels:  # garante que apenas os pods com o rotulo app : nginx-deployment sejam gerenciados por este deployment
      app: nginx-deployment
  strategy: {}  # controla como o deployment aplica atualizações nos pods. 
# End confg deployment
# Start config templates para os pods
  template:  # define o modelo usado para criar os pods
    metadata: # os rótulos dos pods sao especificados aqui. eles devem coincidir com os rotules definidos no selector do deployment
      labels:
        app: nginx-deployment
    spec: # contem as especificações para os containers dentro dos pods
      containers: # lista os containers que serão executados
      - image: nginx # especifica a image
        name: nginx # nome do container
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.3"
            memory: "64Mi"
      
      
