services:
  giropops-senhas:
    build: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - strigus:/strigus
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M  
        limits:
          cpus: '0.5'
          memory: 256M  
    networks:
      - giropops
  
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - strigus:/strigus
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]        
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - giropops

networks:
  giropops:
    driver: bridge

volumes:
  strigus:
