version: '3.5'

services:
  mariadb:
    image: mariadb:10.5  # Usando a imagem do MariaDB
    container_name: zabbix-mariadb
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: "@#mysql8520@#"
      MYSQL_ROOT_PASSWORD: "@#root8520@#"
    volumes:
      - /data/docker/mysql:/var/lib/mysql  # Volume externo para MariaDB
    restart: unless-stopped
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mariadb  # Alterado para 'mariadb'
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: "@#mysql8520@#"
    volumes:
      - /data/docker/zabbix:/var/lib/zabbix  # Volume externo para Zabbix
    depends_on:
      - mariadb  # Alterado para 'mariadb'
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mariadb  # Alterado para 'mariadb'
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: "@#mysql8520@#"
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/London
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - zabbix-network

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    restart: unless-stopped
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge

volumes:
  zabbix_server_data:
  mysql_data:
